require('colors');
module.exports = [
  '                                                                               '.black + '\n',
  '                                 '.black + '              '.bgYellow + '                               '.black + '\n',
  '                             '.black + '                      '.bgYellow + '                             '.black + '\n',
  '                        '.black + '                              '.bgYellow + '                          '.black + '\n',
  '                     '.black + '                                     '.bgYellow + '                      '.black + '\n',
  '                   '.black + '                                         '.bgYellow + '                    '.black + '\n',
  '                '.black + '                                              '.bgYellow + '                  '.black + '\n',
  '              '.black + '                                                  '.bgYellow + '                '.black + '\n',
  '            '.black + '                                                      '.bgYellow + '              '.black + '\n',
  '          '.black + '                                                        '.bgYellow + '              '.black + '\n',
  '         '.black + '      '.bgYellow + '+7Z7+'.black + '                             '.bgYellow + '+7Z7I'.black + '              '.bgYellow + '            '.black + '\n',
  '        '.black + '    '.bgYellow + 'ZMMMMMMMMM7'.black + '                      '.bgYellow + '=DMMMMMMMMMN?'.black + '           '.bgYellow + '           '.black + '\n',
  '       '.black + '   '.bgYellow + '=MMN='.black + '    '.bgWhite + '.DMMM7'.black + '                   '.bgYellow + 'MMMD'.black + '       '.bgWhite + 'MMMMI'.black + '          '.bgYellow + '          '.black + '\n',
  '      '.black + '   '.bgYellow + '+MM='.black + '     '.bgWhite + ' MMMMMMN'.black + '                '.bgYellow + 'IMMZ'.black + '       '.bgWhite + '=MMMMMMD'.black + '          '.bgYellow + '         '.black + '\n',
  '     '.black + '    '.bgYellow + 'MMI'.black + '     '.bgWhite + '.MMMMMMMMN'.black + '              '.bgYellow + '?MM,'.black + '       '.bgWhite + '.MMMMMMMMN'.black + '          '.bgYellow + '        '.black + '\n',
  '     '.black + '   '.bgYellow + 'DM8'.black + '      '.bgWhite + '.8MMMMMMMM7'.black + '             '.bgYellow + 'MM='.black + '        '.bgWhite + 'DDMMMMMMMM?'.black + '          '.bgYellow + '       '.black + '\n',
  '    '.black + '    '.bgYellow + 'MM'.black + '        '.bgWhite + '. MMMMM?MM'.black + '            '.bgYellow + '8M8'.black + '          '.bgWhite + '.MMMMMM=MM'.black + '          '.bgYellow + '       '.black + '\n',
  '    '.black + '   '.bgYellow + '+MM'.black + '         '.bgWhite + '...,...MM'.black + '           '.bgYellow + 'MMM'.black + '            '.bgWhite + '..,,...MM?'.black + '          '.bgYellow + '      '.black + '\n',
  '   '.black + '    '.bgYellow + '?M'.black + '                '.bgWhite + 'MM='.black + '           '.bgYellow + 'MM.'.black + '                  '.bgWhite + 'DMZ'.black + '           '.bgYellow + '     '.black + '\n',
  '   '.black + '    '.bgYellow + '?M'.black + '                '.bgWhite + 'MM='.black + '           '.bgYellow + '=MM'.black + '                  '.bgWhite + 'DM7'.black + '           '.bgYellow + '     '.black + '\n',
  '   '.black + '    '.bgYellow + '=MM'.black + '               '.bgWhite + 'MM='.black + '           '.bgYellow + 'MM:.'.black + '                 '.bgWhite + 'MM+'.black + '           '.bgYellow + '     '.black + '\n',
  '  '.black + '      '.bgYellow + 'NMM'.black + '             '.bgWhite + '/MMN'.black + '            '.bgYellow + ' MMM'.black + '               '.bgWhite + 'MMMM'.black + '            '.bgYellow + '     '.black + '\n',
  '  '.black + '       '.bgYellow + '$77777777777777777'.black + '              '.bgYellow + '777$777$777$777$777$$'.black + '             '.bgYellow + '     '.black + '\n',
  '  '.black + '                                                                         '.bgYellow + '     '.black + '\n',
  '  '.black + '                                                                         '.bgYellow + '     '.black + '\n',
  '  '.black + '                                                                         '.bgYellow + '     '.black + '\n',
  '   '.black + '       '.bgYellow + 'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII??IIIIIIIIIIII='.black + '             '.bgYellow + '     '.black + '\n',
  '   '.black + '       '.bgYellow + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.black + '            '.bgYellow + '      '.black + '\n',
  '    '.black + '        '.bgYellow + '+MMZ'.black + '                                            '.bgMagenta + 'MM+'.black + '           '.bgYellow + '      '.black + '\n',
  '    '.black + '        '.bgYellow + '=MM'.black + '                                             '.bgMagenta + 'NM8'.black + '           '.bgYellow + '      '.black + '\n',
  '    '.black + '         '.bgYellow + 'NMD'.black + '                                            '.bgMagenta + 'DMM'.black + '           '.bgYellow + '      '.black + '\n',
  '     '.black + '        '.bgYellow + '?MM'.black + '                                             '.bgMagenta + 'MM'.black + '          '.bgYellow + '       '.black + '\n',
  '     '.black + '         '.bgYellow + 'MMD'.black + '                                           '.bgMagenta + '8MM'.black + '         '.bgYellow + '        '.black + '\n',
  '      '.black + '        '.bgYellow + '=MM8'.black + '                                          '.bgMagenta + 'MMZ'.black + '         '.bgYellow + '        '.black + '\n',
  '       '.black + '        '.bgYellow + 'IMM'.black + '                                          '.bgMagenta + 'MM'.black + '         '.bgYellow + '         '.black + '\n',
  '        '.black + '        '.bgYellow + '8MM'.black + '                                        '.bgMagenta + 'MM '.black + '        '.bgYellow + '          '.black + '\n',
  '         '.black + '        '.bgYellow + '8MM'.black + '                  '.bgMagenta + ',,,mmmmmmmmm'.bgMagenta + '        '.bgMagenta + 'MMN'.black + '        '.bgYellow + '           '.black + '\n',
  '          '.black + '        '.bgYellow + 'NMM'.black + '               '.bgMagenta + ',MMMMMMMMMMMMMMM'.bgMagenta + '     '.bgMagenta + 'MMM'.black + '        '.bgYellow + '            '.black + '\n',
  '           '.black + '        '.bgYellow + '$MM8'.black + '           '.bgMagenta + ',MMMMMMMMMMMMMMMMMMM'.bgMagenta + ' '.bgMagenta + 'DMM8'.black + '       '.bgYellow + '              '.black + '\n',
  '             '.black + '       '.bgYellow + '=MMM'.black + '         '.bgMagenta + ',MMMMMMMMMMMMMMMMMMMM'.bgMagenta + 'MMM='.black + '        '.bgYellow + '              '.black + '\n',
  '               '.black + '       '.bgYellow + 'ZMMM'.black + '      '.bgMagenta + ',MMMMMMMMMMMMMMMMMM'.bgMagenta + '8MMM7'.black + '        '.bgYellow + '                '.black + '\n',
  '                '.black + '        '.bgYellow + 'MMMM'.black + '    MMMMMMMMMMMMMMMM'.bgMagenta + '7MMMM7'.black + '        '.bgYellow + '                  '.black + '\n',
  '                  '.black + '        '.bgYellow + ' MMMMD='.black + 'MMMMMMMMMM'.bgMagenta + ' ZMMMMM8'.black + '         '.bgYellow + '                    '.black + '\n',
  '                     '.black + '        '.bgYellow + '?NMMMMMMMMMMMMMMM +'.black + '         '.bgYellow + '                       '.black + '\n',
  '                        '.black + '           '.bgYellow + '=+???='.black + '             '.bgYellow + '                          '.black + '\n',
  '                             '.black + '                     '.bgYellow + '                              '.black + '\n',
  '                                                                               '.black + '\n',
];
