require('colors');
module.exports = [
  '                                                                               '.black + '\n',
  '                                 '.black + '              '.bgYellow + '                                '.black + '\n',
  '                             '.black + '                      '.bgYellow + '                            '.black + '\n',
  '                        '.black + '                              '.bgYellow + '                         '.black + '\n',
  '                     '.black + '                                     '.bgYellow + '                     '.black + '\n',
  '                   '.black + '                                         '.bgYellow + '                   '.black + '\n',
  '                '.black + '                                              '.bgYellow + '                 '.black + '\n',
  '              '.black + '                                                  '.bgYellow + '               '.black + '\n',
  '            '.black + '                                                      '.bgYellow + '             '.black + '\n',
  '          '.black + '                                                        '.bgYellow + '             '.black + '\n',
  '         '.black + '      '.bgYellow + '     '.black + '                             '.bgYellow + '     '.black + '              '.bgYellow + '           '.black + '\n',
  '        '.black + '    '.bgYellow + '           '.black + '                      '.bgYellow + '             '.black + '           '.bgYellow + '          '.black + '\n',
  '       '.black + '   '.bgYellow + '     '.black + '    '.bgWhite + '      '.black + '                   '.bgYellow + '    '.black + '       '.bgWhite + '     '.black + '          '.bgYellow + '         '.black + '\n',
  '      '.black + '   '.bgYellow + '    '.black + '     '.bgWhite + '        '.black + '                '.bgYellow + '    '.black + '       '.bgWhite + '        '.black + '          '.bgYellow + '        '.black + '\n',
  '     '.black + '    '.bgYellow + '   '.black + '     '.bgWhite + '          '.black + '              '.bgYellow + '    '.black + '       '.bgWhite + '          '.black + '          '.bgYellow + '       '.black + '\n',
  '     '.black + '   '.bgYellow + '   '.black + '      '.bgWhite + '           '.black + '             '.bgYellow + '   '.black + '        '.bgWhite + '           '.black + '          '.bgYellow + '      '.black + '\n',
  '    '.black + '    '.bgYellow + '  '.black + '        '.bgWhite + '          '.black + '            '.bgYellow + '   '.black + '          '.bgWhite + '          '.black + '          '.bgYellow + '      '.black + '\n',
  '    '.black + '   '.bgYellow + '   '.black + '         '.bgWhite + '         '.black + '           '.bgYellow + '   '.black + '            '.bgWhite + '          '.black + '          '.bgYellow + '     '.black + '\n',
  '   '.black + '    '.bgYellow + '  '.black + '                '.bgWhite + '   '.black + '           '.bgYellow + '   '.black + '                  '.bgWhite + '   '.black + '           '.bgYellow + '     '.black + '\n',
  '   '.black + '    '.bgYellow + '  '.black + '                '.bgWhite + '   '.black + '           '.bgYellow + '   '.black + '                  '.bgWhite + '   '.black + '           '.bgYellow + '     '.black + '\n',
  '   '.black + '    '.bgYellow + '   '.black + '               '.bgWhite + '   '.black + '           '.bgYellow + '    '.black + '                 '.bgWhite + '   '.black + '           '.bgYellow + '     '.black + '\n',
  '  '.black + '      '.bgYellow + '   '.black + '             '.bgWhite + '    '.black + '            '.bgYellow + '    '.black + '               '.bgWhite + '    '.black + '            '.bgYellow + '    '.black + '\n',
  '  '.black + '       '.bgYellow + '                  '.black + '              '.bgYellow + '                     '.black + '             '.bgYellow + '    '.black + '\n',
  '  '.black + '                                                                         '.bgYellow + '    '.black + '\n',
  '  '.black + '                                                                         '.bgYellow + '    '.black + '\n',
  '  '.black + '                                                                         '.bgYellow + '    '.black + '\n',
  '   '.black + '       '.bgYellow + '                                                    '.black + '             '.bgYellow + '    '.black + '\n',
  '   '.black + '       '.bgYellow + '                                                    '.black + '            '.bgYellow + '     '.black + '\n',
  '    '.black + '        '.bgYellow + '    '.black + '                                            '.bgMagenta + '   '.black + '           '.bgYellow + '     '.black + '\n',
  '    '.black + '        '.bgYellow + '   '.black + '                                             '.bgMagenta + '   '.black + '           '.bgYellow + '     '.black + '\n',
  '    '.black + '         '.bgYellow + '   '.black + '                                            '.bgMagenta + '   '.black + '           '.bgYellow + '     '.black + '\n',
  '     '.black + '        '.bgYellow + '   '.black + '                                             '.bgMagenta + '  '.black + '          '.bgYellow + '      '.black + '\n',
  '     '.black + '         '.bgYellow + '   '.black + '                                           '.bgMagenta + '   '.black + '         '.bgYellow + '       '.black + '\n',
  '      '.black + '        '.bgYellow + '    '.black + '                                          '.bgMagenta + '   '.black + '         '.bgYellow + '       '.black + '\n',
  '       '.black + '        '.bgYellow + '   '.black + '                                          '.bgMagenta + '  '.black + '         '.bgYellow + '        '.black + '\n',
  '        '.black + '        '.bgYellow + '   '.black + '                                        '.bgMagenta + '   '.black + '        '.bgYellow + '         '.black + '\n',
  '         '.black + '        '.bgYellow + '   '.black + '                  '.bgMagenta + ',,,mmmmmmmmm'.bgMagenta + '        '.bgMagenta + '   '.black + '        '.bgYellow + '          '.black + '\n',
  '          '.black + '        '.bgYellow + '   '.black + '               '.bgMagenta + ',MMMMMMMMMMMMMMM'.bgMagenta + '     '.bgMagenta + '   '.black + '        '.bgYellow + '           '.black + '\n',
  '           '.black + '        '.bgYellow + '    '.black + '           '.bgMagenta + ',MMMMMMMMMMMMMMMMMMM'.bgMagenta + ' '.bgMagenta + '    '.black + '       '.bgYellow + '             '.black + '\n',
  '             '.black + '       '.bgYellow + '    '.black + '         '.bgMagenta + ',MMMMMMMMMMMMMMMMMMMM'.bgMagenta + '    '.black + '        '.bgYellow + '             '.black + '\n',
  '               '.black + '       '.bgYellow + '    '.black + '      '.bgMagenta + ',MMMMMMMMMMMMMMMMMM'.bgMagenta + '     '.black + '        '.bgYellow + '               '.black + '\n',
  '                '.black + '        '.bgYellow + '    '.black + '    MMMMMMMMMMMMMMMM'.bgMagenta + '      '.black + '        '.bgYellow + '                 '.black + '\n',
  '                  '.black + '        '.bgYellow + '       '.black + 'MMMMMMMMMM'.bgMagenta + '        '.black + '         '.bgYellow + '                   '.black + '\n',
  '                     '.black + '        '.bgYellow + '                   '.black + '         '.bgYellow + '                      '.black + '\n',
  '                        '.black + '           '.bgYellow + '      '.black + '             '.bgYellow + '                         '.black + '\n',
  '                             '.black + '                     '.bgYellow + '                             '.black + '\n',
  '                                                                               '.black + '\n',
];
