require('colors');
module.exports = [
  '                                                                            '.black + '\n',
  '                                '.black + '       '.bgYellow + '                                     '.black + '\n',
  '                         '.black + '                     '.bgYellow + '                              '.black + '\n',
  '                     '.black + '                             '.bgYellow + '                          '.black + '\n',
  '                  '.black + '                                   '.bgYellow + '                       '.black + '\n',
  '                '.black + '                                       '.bgYellow + '                     '.black + '\n',
  '              '.black + '                                           '.bgYellow + '                   '.black + '\n',
  '            '.black + '                                               '.bgYellow + '                 '.black + '\n',
  '          '.black + '                                                   '.bgYellow + '               '.black + '\n',
  '         '.black + '                                                     '.bgYellow + '              '.black + '\n',
  '        '.black + '    '.bgYellow + '     '.black + '                           '.bgYellow + '      '.black + '             '.bgYellow + '             '.black + '\n',
  '       '.black + '  '.bgYellow + '     '.black + '  '.bgWhite + '    '.black + '                     '.bgYellow + '     '.black + '  '.bgWhite + '     '.black + '           '.bgYellow + '            '.black + '\n',
  '      '.black + '  '.bgYellow + '   '.black + '        '.bgWhite + '   '.black + '                 '.bgYellow + '    '.black + '         '.bgWhite + '   '.black + '          '.bgYellow + '           '.black + '\n',
  '     '.black + '  '.bgYellow + '   '.black + '   '.bgWhite + '      '.black + ' '.bgWhite + '   '.black + '               '.bgYellow + '   '.black + '   '.bgWhite + '        '.black + ' '.bgWhite + '   '.black + '          '.bgYellow + '          '.black + '\n',
  '    '.black + '  '.bgYellow + '   '.black + '   '.bgWhite + '            '.black + '             '.bgYellow + '   '.black + '   '.bgWhite + '          '.black + '  '.bgWhite + '  '.black + '          '.bgYellow + '         '.black + '\n',
  '    '.black + '  '.bgYellow + '  '.black + '   '.bgWhite + '          '.black + ' '.bgWhite + '  '.black + '             '.bgYellow + '  '.black + '    '.bgWhite + '           '.black + ' '.bgWhite + '   '.black + '         '.bgYellow + '         '.black + '\n',
  '   '.black + '   '.bgYellow + '  '.black + '   '.bgWhite + '          '.black + '  '.bgWhite + '  '.black + '           '.bgYellow + '  '.black + '     '.bgWhite + '           '.black + '  '.bgWhite + '  '.black + '          '.bgYellow + '        '.black + '\n',
  '   '.black + '  '.bgYellow + '   '.black + '   '.bgWhite + '          '.black + '  '.bgWhite + '  '.black + '           '.bgYellow + '  '.black + '     '.bgWhite + '           '.black + '  '.bgWhite + '  '.black + '          '.bgYellow + '        '.black + '\n',
  '  '.black + '   '.bgYellow + '   '.black + '    '.bgWhite + '        '.black + '   '.bgWhite + '  '.black + '           '.bgYellow + '  '.black + '      '.bgWhite + '         '.black + '   '.bgWhite + '  '.black + '           '.bgYellow + '       '.black + '\n',
  '  '.black + '    '.bgYellow + '  '.black + '      '.bgCyan + '   '.black + '      '.bgCyan + '  '.black + '           '.bgYellow + '  '.black + '         '.bgCyan + '   '.black + '      '.bgCyan + '  '.black + '           '.bgYellow + '       '.black + '\n',
  '  '.black + '    '.bgYellow + '  '.black + '              '.bgCyan + '  '.black + '            '.bgYellow + '  '.black + '                  '.bgCyan + '  '.black + '           '.bgYellow + '       '.black + '\n',
  '  '.black + '     '.bgYellow + '                 '.black + '             '.bgYellow + '           '.black + '    '.bgCyan + '     '.black + '            '.bgYellow + '       '.black + '\n',
  '  '.black + '                                              '.bgYellow + '    '.bgCyan + '                 '.bgYellow + '       '.black + '\n',
  '  '.black + '                                               '.bgYellow + '   '.bgCyan + '                 '.bgYellow + '       '.black + '\n',
  '  '.black + '                                                                   '.bgYellow + '       '.black + '\n',
  '  '.black + '                               '.bgYellow + '   '.black + '                                 '.bgYellow + '       '.black + '\n',
  '  '.black + '                        '.bgYellow + '       '.black + '   '.bgMagenta + '     '.black + '                            '.bgYellow + '       '.black + '\n',
  '  '.black + '                     '.bgYellow + '   '.black + '               '.bgMagenta + '   '.black + '                         '.bgYellow + '       '.black + '\n',
  '   '.black + '                  '.bgYellow + '  '.black + '                     '.bgMagenta + '  '.black + '                      '.bgYellow + '        '.black + '\n',
  '   '.black + '                '.bgYellow + '  '.black + '                         '.bgMagenta + '  '.black + '                    '.bgYellow + '        '.black + '\n',
  '    '.black + '              '.bgYellow + '  '.black + '                           '.bgMagenta + '  '.black + '                  '.bgYellow + '         '.black + '\n',
  '    '.black + '             '.bgYellow + '  '.black + '                             '.bgMagenta + '  '.black + '                 '.bgYellow + '         '.black + '\n',
  '     '.black + '           '.bgYellow + '  '.black + '                         +m????'.bgMagenta + '  '.black + '               '.bgYellow + '          '.black + '\n',
  '      '.black + '         '.bgYellow + '  '.black + '                       +?????????'.bgMagenta + '  '.black + '             '.bgYellow + '           '.black + '\n',
  '       '.black + '        '.bgYellow + '  '.black + '                     +????????????'.bgMagenta + '  '.black + '           '.bgYellow + '            '.black + '\n',
  '        '.black + '       '.bgYellow + '  '.black + '                    +??????????????'.bgMagenta + ' '.black + '          '.bgYellow + '             '.black + '\n',
  '         '.black + '      '.bgYellow + '  '.black + '                   +???????????????'.bgMagenta + '  '.black + '        '.bgYellow + '              '.black + '\n',
  '           '.black + '     '.bgYellow + '. '.black + '                  ????????????????'.bgMagenta + '  '.black + '      '.bgYellow + '                '.black + '\n',
  '            '.black + '    '.bgYellow + '                                        '.black + '   '.bgYellow + '                 '.black + '\n',
  '              '.black + '                                           '.bgYellow + '                   '.black + '\n',
  '                '.black + '                                       '.bgYellow + '                     '.black + '\n',
  '                  '.black + '                                   '.bgYellow + '                       '.black + '\n',
  '                     '.black + '                             '.bgYellow + '                          '.black + '\n',
  '                         '.black + '                     '.bgYellow + '                              '.black + '\n',
  '                                                                            '.black + '\n',
];
