require('colors');
module.exports = [
  '                                                                            '.black + '\n',
  '                                '.black + 'MMMMMMM'.yellow + '                                     '.black + '\n',
  '                         '.black + 'MMMMMMMMMMMMMMMMMMMMM'.yellow + '                              '.black + '\n',
  '                     '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '                          '.black + '\n',
  '                  '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '                       '.black + '\n',
  '                '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '                     '.black + '\n',
  '              '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '                   '.black + '\n',
  '            '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '                 '.black + '\n',
  '          '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '               '.black + '\n',
  '         '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '              '.black + '\n',
  '        '.black + 'MMMM'.yellow + '     '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '      '.black + 'MMMMMMMMMMMMM'.yellow + '             '.black + '\n',
  '       '.black + 'MM'.yellow + '     '.black + 'MM'.white + '    '.black + 'MMMMMMMMMMMMMMMMMMMMM'.yellow + '     '.black + 'MM'.white + '     '.black + 'MMMMMMMMMMM'.yellow + '            '.black + '\n',
  '      '.black + 'MM'.yellow + '   '.black + 'MMMMMMMM'.white + '   '.black + 'MMMMMMMMMMMMMMMMM'.yellow + '    '.black + 'MMMMMMMMM'.white + '   '.black + 'MMMMMMMMMM'.yellow + '           '.black + '\n',
  '     '.black + 'MM'.yellow + '   '.black + 'MMM'.white + '      '.black + 'MM'.white + '  '.black + 'MMMMMMMMMMMMMMM'.yellow + '   '.black + 'MMM'.white + '        '.black + 'MM'.white + '  '.black + 'MMMMMMMMMM'.yellow + '          '.black + '\n',
  '    '.black + 'MM'.yellow + '   '.black + 'MMM'.white + '        '.black + 'MM'.white + '  '.black + 'MMMMMMMMMMMMM'.yellow + '   '.black + 'MMM'.white + '          '.black + 'MM'.white + '  '.black + 'MMMMMMMMMM'.yellow + '         '.black + '\n',
  '    '.black + 'MM'.yellow + '  '.black + 'MMM'.white + '          '.black + 'M'.white + '  '.black + 'MMMMMMMMMMMMM'.yellow + '  '.black + 'MMMM'.white + '           '.black + 'M'.white + '   '.black + 'MMMMMMMMM'.yellow + '         '.black + '\n',
  '   '.black + 'MMM'.yellow + '  '.black + 'MMM'.white + '          '.black + 'MM'.white + '  '.black + 'MMMMMMMMMMM'.yellow + '  '.black + 'MMMMM'.white + '           '.black + 'MM'.white + '  '.black + 'MMMMMMMMMM'.yellow + '        '.black + '\n',
  '   '.black + 'MM'.yellow + '   '.black + 'MMM'.white + '          '.black + 'MM'.white + '  '.black + 'MMMMMMMMMMM'.yellow + '  '.black + 'MMMMM'.white + '           '.black + 'MM'.white + '  '.black + 'MMMMMMMMMM'.yellow + '        '.black + '\n',
  '  '.black + 'MMM'.yellow + '   '.black + 'MMMM'.white + '        '.black + 'MMM'.white + '  '.black + 'MMMMMMMMMMM'.yellow + '  '.black + 'MMMMMM'.white + '         '.black + 'MMM'.white + '  '.black + 'MMMMMMMMMMM'.yellow + '       '.black + '\n',
  '  '.black + 'MMMM'.yellow + '  '.black + 'MMMMMM'.cyan + '   '.black + 'MMMMMM'.cyan + '  '.black + 'MMMMMMMMMMM'.yellow + '  '.black + 'MMMMMMMMM'.cyan + '   '.black + 'MMMMMM'.cyan + '  '.black + 'MMMMMMMMMMM'.yellow + '       '.black + '\n',
  '  '.black + 'MMMM'.yellow + '  '.black + 'MMMMMMMMMMMMMM'.cyan + '  '.black + 'MMMMMMMMMMMM'.yellow + '  '.black + 'MMMMMMMMMMMMMMMMMM'.cyan + '  '.black + 'MMMMMMMMMMM'.yellow + '       '.black + '\n',
  '  '.black + 'MMMMM'.yellow + '                 '.black + 'MMMMMMMMMMMMM'.yellow + '           '.black + 'MMMM'.cyan + '     '.black + 'MMMMMMMMMMMM'.yellow + '       '.black + '\n',
  '  '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + 'MMMM'.cyan + 'MMMMMMMMMMMMMMMMM'.yellow + '       '.black + '\n',
  '  '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + 'MMM'.cyan + 'MMMMMMMMMMMMMMMMM'.yellow + '       '.black + '\n',
  '  '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '       '.black + '\n',
  '  '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '   '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '       '.black + '\n',
  '  '.black + 'MMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '       '.black + 'MMM'.magenta + '     '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '       '.black + '\n',
  '  '.black + 'MMMMMMMMMMMMMMMMMMMMM'.yellow + '   '.black + 'MMMMMMMMMMMMMMM'.magenta + '   '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '       '.black + '\n',
  '   '.black + 'MMMMMMMMMMMMMMMMMM'.yellow + '  '.black + 'MMMMMMMMMMMMMMMMMMMMM'.magenta + '  '.black + 'MMMMMMMMMMMMMMMMMMMMMM'.yellow + '        '.black + '\n',
  '   '.black + 'MMMMMMMMMMMMMMMM'.yellow + '  '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMM'.magenta + '  '.black + 'MMMMMMMMMMMMMMMMMMMM'.yellow + '        '.black + '\n',
  '    '.black + 'MMMMMMMMMMMMMM'.yellow + '  '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMM'.magenta + '  '.black + 'MMMMMMMMMMMMMMMMMM'.yellow + '         '.black + '\n',
  '    '.black + 'MMMMMMMMMMMMM'.yellow + '  '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.magenta + '  '.black + 'MMMMMMMMMMMMMMMMM'.yellow + '         '.black + '\n',
  '     '.black + 'MMMMMMMMMMM'.yellow + '  '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMM'.magenta + '+m????'.white + '  '.black + 'MMMMMMMMMMMMMMM'.yellow + '          '.black + '\n',
  '      '.black + 'MMMMMMMMM'.yellow + '  '.black + 'MMMMMMMMMMMMMMMMMMMMMMM'.magenta + '+?????????'.white + '  '.black + 'MMMMMMMMMMMMM'.yellow + '           '.black + '\n',
  '       '.black + 'MMMMMMMM'.yellow + '  '.black + 'MMMMMMMMMMMMMMMMMMMMM'.magenta + '+????????????'.white + '  '.black + 'MMMMMMMMMMM'.yellow + '            '.black + '\n',
  '        '.black + 'MMMMMMM'.yellow + '  '.black + 'MMMMMMMMMMMMMMMMMMMM'.magenta + '+??????????????'.white + ' '.black + 'MMMMMMMMMM'.yellow + '             '.black + '\n',
  '         '.black + 'MMMMMM'.yellow + '  '.black + 'MMMMMMMMMMMMMMMMMMM'.magenta + '+???????????????'.white + '  '.black + 'MMMMMMMM'.yellow + '              '.black + '\n',
  '           '.black + 'MMMMM'.yellow + '. '.black + 'MMMMMMMMMMMMMMMMMM'.magenta + '????????????????'.white + '  '.black + 'MMMMMM'.yellow + '                '.black + '\n',
  '            '.black + 'MMMM'.yellow + '                                        '.black + 'MMM'.yellow + '                 '.black + '\n',
  '              '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '                   '.black + '\n',
  '                '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '                     '.black + '\n',
  '                  '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '                       '.black + '\n',
  '                     '.black + 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.yellow + '                          '.black + '\n',
  '                         '.black + 'MMMMMMMMMMMMMMMMMMMMM'.yellow + '                              '.black + '\n',
  '                                                                            '.black + '\n',
];
